### ISSUE TITLE
Is this a similar outcome as using gzip?

### ISSUE THREAD

**Issue by polarathene** [soluml/SweatMap#2]
How does this compare to gzip? Do they compliment one another or achieve the same goal of reduced filesize for minimiznig bandwidth?(assuming uncompressed processing of gzip and size once received has minimal impact on the user)

**Comment by soluml** [comment]
SweatMap is just a mapping of key/value pairs where a string goes in and an obfuscated string comes out.  There's really no comparison between compression algorithm's like Gzip and a tool like SweatMap... they're different things.

They can be used to compliment one another though.  For example, I'm using SweatMap to obfuscate class names in my web based projects. While definitely not a replacement for Gzip (which you should be using), it does help be save additional bytes from my final output.
